### PR TITLE
Feature findbugs fix

### LINKED ISSUE #93: findbugs errors
Findbugs errors
[INFO] Write to static field com.sem46.core.Assets.textures from instance method com.sem46.core.Assets.load() [com.sem46.core.Assets] At Assets.java:[line 36]
[INFO] Unread field: com.sem46.core.PlayerPhysicsComponent.frictionCoefficient; should this field be static? [com.sem46.core.PlayerPhysicsComponent] At PlayerPhysicsComponent.java:[line 17]

### PR DESCRIPTION
**Pull request by Tclv**
fixes #93
<bug

### CODE REVIEW

**Comment by jonascarpay** [comment]
👍🏿

File: core/src/main/java/com/sem46/core/Assets.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
  */
 public final class Assets {
   /** Hashmap storing textures. */
-  private static HashMap<String, Texture> textures;
+  private HashMap<String, Texture> textures;
```
Comment (ashay123) [inline core/src/main/java/com/sem46/core/Assets.java]: Why not keep this static and initialise (textures = new HashMap<String, Texture>();) it in the constructor?
